race = Biascreate!(name: "race")
religion = Bias.create!(name: "religion")
sexual_orientation = Bias.create!(name: "sexual orientation")
ethnicity = Bias.create!(name: "ethnicity or national origin")
disability = Bias.create!(name: "disability")
multiple_bias = Bias.create!(name: "multiple bias")

personal_offense = Offense.create!(name: "crimes against persons")
property_offense = Offense.create!(name: "crimes against property")

personal_offense.sub_types.create!(name:"murder and nonnegligent manslaughter")
personal_offense.sub_types.create!(name:"forcible rape")
personal_offense.sub_types.create!(name:"aggravated assault")
personal_offense.sub_types.create!(name:"simple assault")
personal_offense.sub_types.create!(name:"intimidation")
personal_offense.sub_types.create!(name:"other")

white_bias = race.sub_types.create!(name: "anti white")
race.sub_types.create!(name: "anti black")
race.sub_types.create!(name: "anti american indian or alaskan native")
race.sub_types.create!(name: "anti asian pacific islander")
race.sub_types.create!(name: "anti multiple races")

religion.sub_types.create!(name: "anti jewish")
religion.sub_types.create!(name: "anti catholic")
religion.sub_types.create!(name: "anti protestant")
religion.sub_types.create!(name: "anti islamic")
religion.sub_types.create!(name: "anti multiple religions")
religion.sub_types.create!(name: "anti atheism agnostic etc")
