race = BiasType.create!(name: "race")
religion = BiasType.create!(name: "religion")
sexual_orientation = BiasType.create!(name: "sexual orientation")
ethnicity = BiasType.create!(name: "ethnicity or national origin")
disability = BiasType.create!(name: "disability")
multiple_bias = BiasType.create!(name: "multiple bias")

personal_offense = OffenseType.create!(name: "crimes against persons")
property_offense = OffenseType.create!(name: "crimes against property")

personal_offense.offenses.create!(name:"murder and nonnegligent manslaughter")
personal_offense.offenses.create!(name:"forcible rape")
personal_offense.offenses.create!(name:"aggravated assault")
personal_offense.offenses.create!(name:"simple assault")
personal_offense.offenses.create!(name:"intimidation")
personal_offense.offenses.create!(name:"other")

white_bias = race.biases.create!(name: "anti white", total_incidents: 716)
race.biases.create!(name: "anti black", total_incidents: 2876)
race.biases.create!(name: "anti american indian or alaskan native", total_incidents: 54)
race.biases.create!(name: "anti asian pacific islander", total_incidents: 137)
race.biases.create!(name: "anti multiple races", total_incidents: 206)

religion.biases.create!(name: "anti jewish", total_incidents: 1013)
religion.biases.create!(name: "anti catholic", total_incidents: 75)
religion.biases.create!(name: "anti protestant", total_incidents: 56)
religion.biases.create!(name: "anti islamic", total_incidents: 105)
religion.biases.create!(name: "anti multiple religions", total_incidents: 65)
religion.biases.create!(name: "anti atheism agnostic etc", total_incidents: 14)
